/**
 * This file is autogenerated. Do not edit by hand — run `pnpm generate`.
 *
 * Non-local chain deployments live here; local (chainId 31337)
 * deployments live in `./Encora.local.ts` (gitignored) and are merged in
 * at module load. Import by name: `import { Encora } from "~~/contracts/Encora";`
 */
import type { ContractDeployment } from "~~/utils/contract";
import { Encora as Encora_LOCAL } from "./Encora.local";

const REMOTE = {
  11155111: {
    address: "0x046E8D5aC53fFf77d992422fa0c45F9b6F0F9aEd",
    abi: [
      {
        type: "constructor",
        inputs: [
          {
            name: "usdc",
            type: "address",
            internalType: "address",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "USDC",
        inputs: [],
        outputs: [
          {
            name: "",
            type: "address",
            internalType: "contract IERC20",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "confidentialProtocolId",
        inputs: [],
        outputs: [
          {
            name: "",
            type: "uint256",
            internalType: "uint256",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "contentCount",
        inputs: [],
        outputs: [
          {
            name: "",
            type: "uint256",
            internalType: "uint256",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "contentsBySeller",
        inputs: [
          {
            name: "",
            type: "address",
            internalType: "address",
          },
          {
            name: "",
            type: "uint256",
            internalType: "uint256",
          },
        ],
        outputs: [
          {
            name: "",
            type: "uint256",
            internalType: "uint256",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "deactivate",
        inputs: [
          {
            name: "contentId",
            type: "uint256",
            internalType: "uint256",
          },
        ],
        outputs: [],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "getContent",
        inputs: [
          {
            name: "id",
            type: "uint256",
            internalType: "uint256",
          },
        ],
        outputs: [
          {
            name: "",
            type: "tuple",
            internalType: "struct Encora.ContentInfo",
            components: [
              {
                name: "id",
                type: "uint256",
                internalType: "uint256",
              },
              {
                name: "seller",
                type: "address",
                internalType: "address",
              },
              {
                name: "title",
                type: "string",
                internalType: "string",
              },
              {
                name: "description",
                type: "string",
                internalType: "string",
              },
              {
                name: "previewText",
                type: "string",
                internalType: "string",
              },
              {
                name: "encryptedContent",
                type: "bytes",
                internalType: "bytes",
              },
              {
                name: "price",
                type: "uint256",
                internalType: "uint256",
              },
              {
                name: "active",
                type: "bool",
                internalType: "bool",
              },
              {
                name: "createdAt",
                type: "uint256",
                internalType: "uint256",
              },
              {
                name: "category",
                type: "string",
                internalType: "string",
              },
            ],
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "getContentsBySeller",
        inputs: [
          {
            name: "seller",
            type: "address",
            internalType: "address",
          },
        ],
        outputs: [
          {
            name: "",
            type: "uint256[]",
            internalType: "uint256[]",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "getEncryptedKeyHandles",
        inputs: [
          {
            name: "contentId",
            type: "uint256",
            internalType: "uint256",
          },
        ],
        outputs: [
          {
            name: "",
            type: "bytes32[8]",
            internalType: "euint32[8]",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "getPurchasesByBuyer",
        inputs: [
          {
            name: "buyer",
            type: "address",
            internalType: "address",
          },
        ],
        outputs: [
          {
            name: "",
            type: "uint256[]",
            internalType: "uint256[]",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "hasAccess",
        inputs: [
          {
            name: "contentId",
            type: "uint256",
            internalType: "uint256",
          },
          {
            name: "buyer",
            type: "address",
            internalType: "address",
          },
        ],
        outputs: [
          {
            name: "",
            type: "bool",
            internalType: "bool",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "hasPaid",
        inputs: [
          {
            name: "",
            type: "uint256",
            internalType: "uint256",
          },
          {
            name: "",
            type: "address",
            internalType: "address",
          },
        ],
        outputs: [
          {
            name: "",
            type: "bool",
            internalType: "bool",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "listByCategory",
        inputs: [
          {
            name: "category",
            type: "string",
            internalType: "string",
          },
          {
            name: "offset",
            type: "uint256",
            internalType: "uint256",
          },
          {
            name: "limit",
            type: "uint256",
            internalType: "uint256",
          },
        ],
        outputs: [
          {
            name: "",
            type: "tuple[]",
            internalType: "struct Encora.ContentInfo[]",
            components: [
              {
                name: "id",
                type: "uint256",
                internalType: "uint256",
              },
              {
                name: "seller",
                type: "address",
                internalType: "address",
              },
              {
                name: "title",
                type: "string",
                internalType: "string",
              },
              {
                name: "description",
                type: "string",
                internalType: "string",
              },
              {
                name: "previewText",
                type: "string",
                internalType: "string",
              },
              {
                name: "encryptedContent",
                type: "bytes",
                internalType: "bytes",
              },
              {
                name: "price",
                type: "uint256",
                internalType: "uint256",
              },
              {
                name: "active",
                type: "bool",
                internalType: "bool",
              },
              {
                name: "createdAt",
                type: "uint256",
                internalType: "uint256",
              },
              {
                name: "category",
                type: "string",
                internalType: "string",
              },
            ],
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "listContents",
        inputs: [
          {
            name: "offset",
            type: "uint256",
            internalType: "uint256",
          },
          {
            name: "limit",
            type: "uint256",
            internalType: "uint256",
          },
        ],
        outputs: [
          {
            name: "",
            type: "tuple[]",
            internalType: "struct Encora.ContentInfo[]",
            components: [
              {
                name: "id",
                type: "uint256",
                internalType: "uint256",
              },
              {
                name: "seller",
                type: "address",
                internalType: "address",
              },
              {
                name: "title",
                type: "string",
                internalType: "string",
              },
              {
                name: "description",
                type: "string",
                internalType: "string",
              },
              {
                name: "previewText",
                type: "string",
                internalType: "string",
              },
              {
                name: "encryptedContent",
                type: "bytes",
                internalType: "bytes",
              },
              {
                name: "price",
                type: "uint256",
                internalType: "uint256",
              },
              {
                name: "active",
                type: "bool",
                internalType: "bool",
              },
              {
                name: "createdAt",
                type: "uint256",
                internalType: "uint256",
              },
              {
                name: "category",
                type: "string",
                internalType: "string",
              },
            ],
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "purchase",
        inputs: [
          {
            name: "contentId",
            type: "uint256",
            internalType: "uint256",
          },
        ],
        outputs: [],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "purchasesByBuyer",
        inputs: [
          {
            name: "",
            type: "address",
            internalType: "address",
          },
          {
            name: "",
            type: "uint256",
            internalType: "uint256",
          },
        ],
        outputs: [
          {
            name: "",
            type: "uint256",
            internalType: "uint256",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "requestAccess",
        inputs: [
          {
            name: "contentId",
            type: "uint256",
            internalType: "uint256",
          },
        ],
        outputs: [],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "sellerBalance",
        inputs: [
          {
            name: "",
            type: "address",
            internalType: "address",
          },
        ],
        outputs: [
          {
            name: "",
            type: "uint256",
            internalType: "uint256",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "uploadContent",
        inputs: [
          {
            name: "title",
            type: "string",
            internalType: "string",
          },
          {
            name: "description",
            type: "string",
            internalType: "string",
          },
          {
            name: "previewText",
            type: "string",
            internalType: "string",
          },
          {
            name: "encryptedContent",
            type: "bytes",
            internalType: "bytes",
          },
          {
            name: "encSymKeyChunks",
            type: "bytes32[8]",
            internalType: "externalEuint32[8]",
          },
          {
            name: "inputProofs",
            type: "bytes[]",
            internalType: "bytes[]",
          },
          {
            name: "category",
            type: "string",
            internalType: "string",
          },
          {
            name: "price",
            type: "uint256",
            internalType: "uint256",
          },
        ],
        outputs: [
          {
            name: "id",
            type: "uint256",
            internalType: "uint256",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "withdraw",
        inputs: [],
        outputs: [],
        stateMutability: "nonpayable",
      },
      {
        type: "event",
        name: "AccessGranted",
        inputs: [
          {
            name: "id",
            type: "uint256",
            indexed: true,
            internalType: "uint256",
          },
          {
            name: "buyer",
            type: "address",
            indexed: true,
            internalType: "address",
          },
        ],
        anonymous: false,
      },
      {
        type: "event",
        name: "ContentDeactivated",
        inputs: [
          {
            name: "id",
            type: "uint256",
            indexed: true,
            internalType: "uint256",
          },
        ],
        anonymous: false,
      },
      {
        type: "event",
        name: "ContentPurchased",
        inputs: [
          {
            name: "id",
            type: "uint256",
            indexed: true,
            internalType: "uint256",
          },
          {
            name: "buyer",
            type: "address",
            indexed: true,
            internalType: "address",
          },
        ],
        anonymous: false,
      },
      {
        type: "event",
        name: "ContentUploaded",
        inputs: [
          {
            name: "id",
            type: "uint256",
            indexed: true,
            internalType: "uint256",
          },
          {
            name: "seller",
            type: "address",
            indexed: true,
            internalType: "address",
          },
          {
            name: "title",
            type: "string",
            indexed: false,
            internalType: "string",
          },
          {
            name: "category",
            type: "string",
            indexed: false,
            internalType: "string",
          },
        ],
        anonymous: false,
      },
      {
        type: "error",
        name: "ContentNotActive",
        inputs: [],
      },
      {
        type: "error",
        name: "ContentNotFound",
        inputs: [],
      },
      {
        type: "error",
        name: "NotPurchased",
        inputs: [],
      },
      {
        type: "error",
        name: "NotSeller",
        inputs: [],
      },
      {
        type: "error",
        name: "ReentrancyGuardReentrantCall",
        inputs: [],
      },
      {
        type: "error",
        name: "SafeERC20FailedOperation",
        inputs: [
          {
            name: "token",
            type: "address",
            internalType: "address",
          },
        ],
      },
      {
        type: "error",
        name: "SenderNotAllowedToUseHandle",
        inputs: [
          {
            name: "handle",
            type: "bytes32",
            internalType: "bytes32",
          },
          {
            name: "sender",
            type: "address",
            internalType: "address",
          },
        ],
      },
      {
        type: "error",
        name: "WithdrawFailed",
        inputs: [],
      },
      {
        type: "error",
        name: "ZamaProtocolUnsupported",
        inputs: [],
      },
    ],
    deployedOnBlock: 10826864,
  },
} as const;

export const Encora = {
  ...REMOTE,
  ...Encora_LOCAL,
} as const satisfies Partial<Record<number, ContractDeployment>>;
